name: Inspirafirma AGIO Flow
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  process_intent:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write # จำเป็นสำหรับการเขียนไฟล์

    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: lnspirafirmaGPK
        numOfAssignee: 1

    - name: 'Get intent from issue/PR title and body'
      id: get-intent
      run: |
        EVENT_PAYLOAD=$(cat ${{ github.event_path }})
        if [ "${{ github.event_name }}" == "issues" ]; then
          TITLE=$(echo "$EVENT_PAYLOAD" | jq -r '.issue.title')
          BODY=$(echo "$EVENT_PAYLOAD" | jq -r '.issue.body')
        else
          TITLE=$(echo "$EVENT_PAYLOAD" | jq -r '.pull_request.title')
          BODY=$(echo "$EVENT_PAYLOAD" | jq -r '.pull_request.body')
        fi
        
        echo_wave_data="Title: ${TITLE} | Body: ${BODY}"

        # ใช้วิธีการเขียนแบบ Here Document ซึ่งปลอดภัยสำหรับอักขระพิเศษและข้อความหลายบรรทัด
        {
          echo "echo_wave<<EOF"
          echo "$echo_wave_data"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: 'Send intent to Firestore'
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: 'Write to SoulBase'
      run: |
        # เขียน "คลื่นแห่งความหมาย" ลงใน Firestore
        gcloud firestore documents create "inspirafirma" \
          --collection "inspirafirma" \
          --document-id "${{ github.event.issue.number || github.event.pull_request.number }}" \
          --fields 'echo_wave'="${{ steps.get-intent.outputs.echo_wave }}" \
          --json-payload '{}'

